server {
    listen 80;
    server_name kvastram.com www.kvastram.com;
    return 301 https://odhvica.com$request_uri;
}
server {
    listen 443 ssl;
    server_name kvastram.com www.kvastram.com;
    ssl_certificate /etc/letsencrypt/live/odhvica.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/odhvica.com/privkey.pem;
    return 301 https://odhvica.com$request_uri;
}
